### ISSUE TITLE
About UI Authentication

### ISSUE THREAD

**Issue by bonnlee2024** [netdata/community#101]
How to manage user access， I see that the UI does not require login. My requirement is that only admin can view it.   how to do it?  thanks.

**Comment by ilyam8** [comment]
Hi, @bonnlee2024. You have two options:

- [Put Netdata behind NGINX](https://learn.netdata.cloud/docs/netdata-agent/configuration/running-the-netdata-agent-behind-a-reverse-proxy/nginx) (or any other web server/proxy). Also, see https://learn.netdata.cloud/docs/netdata-agent/securing-netdata-agents/.
- Use Netdata Cloud.
