### ISSUE TITLE
speedtest error

### ISSUE THREAD

**Issue by andrewm4894** [netdata/community#65]
@shyamvalsan im getting this - any idea?

```
/usr/libexec/netdata/plugins.d/../charts.d/speedtest.chart.sh: line 47: 3.351*8/1000: syntax error: invalid arithmetic operator (error token is ".351*8/1000")
```

**Comment by shyamvalsan** [comment]
Let me take a look at it - floating point not playing nice with bash by the look of things.

**Comment by shyamvalsan** [comment]
@andrewm4894 what do you get when you run this from command line? I was expecting an integer value for the bytes fields.

`speedtest --format=csv`

**Comment by andrewm4894** [comment]
```
$ speedtest --format=csv
"Spirit Communications - Columbia, SC","4265","21.6982","1.6555","0","110253582","45004165","1418540416","532675648","https://www.speedtest.net/result/c/de56de28-d821-4b07-9a75-1e4149a5323f","1","38.9758","1.28349","23.387","108.541","17.0321","0.235594","16.892","20.787","20.383","23.738"
```

**Comment by shyamvalsan** [comment]
Ah, I think the comma in the ISP name might be the culprit. I'll open a PR in a bit.

**Comment by shyamvalsan** [comment]
https://github.com/netdata/community/commit/46dcd9e1aae7321eb119e07475cf18a986352723
